# Generated by Django 4.2.21 on 2025-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JewelryInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jewelry_code", models.CharField(max_length=50, unique=True)),
                ("product_tags", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JewelrySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jewelry_code", models.CharField(max_length=50, unique=True)),
                ("product_tags", models.TextField()),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
